name: intercom_flutter
description: Flutter plugin for Intercom integration. Provides in-app messaging
  and help-center Intercom services
version: 2.1.0
author: Maido Käära <m@maido.io>
homepage: https://github.com/v3rm0n/intercom_flutter

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    androidPackage: io.maido.intercom
    pluginClass: IntercomFlutterPlugin

environment:
  sdk: ">=2.0.0 <3.0.0"
  flutter: ">=1.0.0 <2.0.0"
